create table if not exists fare_rates (
  id bigint generated by default as identity primary key,
  service_id text not null,
  service_name text not null,
  zone text not null check (zone in ('inside', 'outside')),
  mile_rate numeric(10, 4) not null default 0,
  minute_rate numeric(10, 4) not null default 0,
  sort_order integer not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (service_id, zone)
);

insert into fare_rates (service_id, service_name, zone, mile_rate, minute_rate, sort_order)
values
  ('uberx', 'UberX', 'inside', 1.28, 0.68, 10),
  ('uberx', 'UberX', 'outside', 1.55, 0.75, 10),
  ('comfort', 'Comfort', 'inside', 1.55, 0.78, 20),
  ('comfort', 'Comfort', 'outside', 1.85, 0.88, 20),
  ('xl', 'UberXL', 'inside', 2.05, 0.95, 30),
  ('xl', 'UberXL', 'outside', 2.45, 1.08, 30),
  ('black', 'Black', 'inside', 3.10, 1.25, 40),
  ('black', 'Black', 'outside', 3.65, 1.45, 40),
  ('black-suv', 'Black SUV', 'inside', 3.65, 1.45, 50),
  ('black-suv', 'Black SUV', 'outside', 4.25, 1.70, 50)
on conflict (service_id, zone) do update set
  service_name = excluded.service_name,
  mile_rate = excluded.mile_rate,
  minute_rate = excluded.minute_rate,
  sort_order = excluded.sort_order,
  active = true,
  updated_at = now();
