create table if not exists public.plate_search_logs (
  id bigint generated by default as identity primary key,
  plate text not null,
  module text not null default 'tlc',
  vehicle_count integer not null default 0,
  violation_count integer not null default 0,
  total_due text not null default '0.00',
  status text not null default 'success',
  created_at timestamptz not null default now()
);

create index if not exists plate_search_logs_created_at_idx
  on public.plate_search_logs (created_at desc);

create index if not exists plate_search_logs_plate_idx
  on public.plate_search_logs (plate);

create table if not exists public.service_info (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists service_info_active_sort_idx
  on public.service_info (active, sort_order, created_at desc);

insert into public.service_info (title, content, active, sort_order)
select
  '出租大楷2020 全表',
  '出租大楷2020，每周650，包保险、牌照、保养， 有全表SUV,BLACK等 有意联系XXXXX',
  true,
  10
where not exists (
  select 1 from public.service_info where title = '出租大楷2020 全表'
);

create table if not exists public.feedback_messages (
  id bigint generated by default as identity primary key,
  message text not null,
  contact text,
  language text,
  page text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists feedback_messages_created_at_idx
  on public.feedback_messages (created_at desc);
