create table if not exists public.plate_search_logs (
  id bigint generated by default as identity primary key,
  plate text not null,
  module text not null default 'tlc',
  vehicle_count integer not null default 0,
  violation_count integer not null default 0,
  total_due text not null default '0.00',
  status text not null default 'success',
  created_at timestamptz not null default now()
);

create index if not exists plate_search_logs_created_at_idx
  on public.plate_search_logs (created_at desc);

create index if not exists plate_search_logs_plate_idx
  on public.plate_search_logs (plate);
